### ISSUE TITLE
java.lang.ClassCastException: java.util.HashMap cannot be cast to java.util.Collection

### ISSUE THREAD

**Issue by tuliogomesbarbosa** [demoiselle/certificate#16]
ClassCastException ao realizar assinatura digital.  Segue a stacktrace:

`java.lang.ClassCastException: java.util.HashMap cannot be cast to java.util.Collection
	at br.gov.frameworkdemoiselle.certificate.keystore.loader.implementation.MSKeyStoreLoader.fixAliases(MSKeyStoreLoader.java:104)
	at br.gov.frameworkdemoiselle.certificate.keystore.loader.implementation.MSKeyStoreLoader.getKeyStore(MSKeyStoreLoader.java:68)
	at br.gov.serpro.efau.applet.view.JDialogAppletProgressOnly.getKeystoreUsuario(JDialogAppletProgressOnly.java:295)
	at br.gov.serpro.efau.applet.view.JDialogAppletProgressOnly.access$100(JDialogAppletProgressOnly.java:32)
	at br.gov.serpro.efau.applet.view.JDialogAppletProgressOnly$2.run(JDialogAppletProgressOnly.java:138)
	at br.gov.serpro.efau.applet.view.JDialogAppletProgressOnly$2.run(JDialogAppletProgressOnly.java:127)
	at java.security.AccessController.doPrivileged(Native Method)
	at br.gov.serpro.efau.applet.view.JDialogAppletProgressOnly.assinar(JDialogAppletProgressOnly.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at sun.plugin.javascript.Trampoline.invoke(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at sun.plugin.javascript.JSClassLoader.invoke(Unknown Source)
	at sun.plugin2.liveconnect.JavaClass$MethodInfo.invoke(Unknown Source)
	at sun.plugin2.liveconnect.JavaClass$MemberBundle.invoke(Unknown Source)
	at sun.plugin2.liveconnect.JavaClass.invoke0(Unknown Source)
	at sun.plugin2.liveconnect.JavaClass.invoke(Unknown Source)
	at sun.plugin2.main.client.LiveConnectSupport$PerAppletInfo$DefaultInvocationDelegate.invoke(Unknown Source)
	at sun.plugin2.main.client.LiveConnectSupport$PerAppletInfo$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.plugin2.main.client.LiveConnectSupport$PerAppletInfo.doObjectOp(Unknown Source)
	at sun.plugin2.main.client.LiveConnectSupport$PerAppletInfo$LiveConnectWorker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)`

O método fixAlises foi originalmente criado para contornar um problema de duplicação de aliases na implementação de keystores do java.

Seguem registros sobre o bug que anotamos durante a correção que fizemos em nossas aplicações que fazem uso do mesmo método, originário da aplicação ReceitaNet: 

> Atualização 26/07/2016: o bug 6672015 foi agrupado no bug 6483657 e resolvido na build 101 do Java 1.8. (http://bugs.java.com/bugdatabase/view_bug.do?bug_id=6483657) 
> Correção aplicada: alteração da variável entries de Collection para Hashmap.
> Com a troca para HashMap, a duplicação de alias não ocorre mais. Entretanto,  é necessário manter compatibilidade com versões anteriores, verificando o tipo  da variável entries antes de fazer o cast para evitar ClassCastException.

**Sugestão de correção:**

//se for uma instância de Map, retorna, pois não precisamos mais do tratamento de duplicidade
`if(field.get(keyStoreVeritable) instanceof Map) return;`
//caso contrário, mantém o tratamento
`entries = (Collection<?>) field.get(keyStoreVeritable);`

**Comment by joserenecampa** [comment]
Bug corrigido a partir da versão 1.1.2.
